/* Runtime integration for official/open maritime snapshots generated by GitHub Actions. */

const officialData = {
  loaded: false,
  avurnav: { items: [] },
  achare: { type: 'FeatureCollection', features: [] },
  resare: { type: 'FeatureCollection', features: [] },
  fairwy: { type: 'FeatureCollection', features: [] },
  seabed: { type: 'FeatureCollection', features: [] },
  cacem: { type: 'FeatureCollection', features: [] },
  sentinel: { observations: [] },
  status: { sources: [] }
};
state.official = officialData;

const esc = value => String(value ?? '')
  .replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;').replaceAll("'", '&#039;');

async function snapshot(path, fallback) {
  try {
    const response = await fetch(`./data/${path}`, { cache: 'no-cache' });
    if (!response.ok) throw new Error(`${response.status}`);
    return await response.json();
  } catch (error) {
    console.warn(`Snapshot unavailable: ${path}`, error);
    return fallback;
  }
}

function featureCount(fc) { return Array.isArray(fc?.features) ? fc.features.length : 0; }
function dataTime(value) {
  if (!value) return 'en attente de synchro';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return 'date inconnue';
  return d.toLocaleString('fr-FR', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' });
}
function sourceHealth() {
  const list = state.official.status?.sources || [];
  const good = list.filter(s => s.ok).length;
  return list.length ? `${good}/${list.length} sources synchronisées` : 'Synchronisation initiale en attente';
}
function propertyLabel(props = {}) {
  return props.layer_name || props.poly_name || props.objnam || props.OBJNAM || props.ref_reg || props._cacem_layer || 'Information maritime';
}
function propertyDetail(props = {}) {
  return props.resume || props.validite || props.restrn || props.RESTRN || props.catrea || props.CATREA || props.natsur || props.NATSUR || props.ref_reg || '';
}

function addGeoLayer(map, id, data, color, opacity = .18, lineWidth = 2) {
  if (!featureCount(data) || map.getSource(id)) return;
  map.addSource(id, { type: 'geojson', data });
  map.addLayer({ id: `${id}-fill`, type: 'fill', source: id, filter: ['==', ['geometry-type'], 'Polygon'], paint: { 'fill-color': color, 'fill-opacity': opacity } });
  map.addLayer({ id: `${id}-line`, type: 'line', source: id, paint: { 'line-color': color, 'line-width': lineWidth, 'line-opacity': .9 } });
  const clickLayer = `${id}-fill`;
  map.on('click', clickLayer, event => {
    const feature = event.features?.[0];
    if (!feature) return;
    const p = feature.properties || {};
    new maplibregl.Popup({ offset: 8 })
      .setLngLat(event.lngLat)
      .setHTML(`<b>${esc(propertyLabel(p))}</b>${propertyDetail(p) ? `<br><small>${esc(propertyDetail(p))}</small>` : ''}`)
      .addTo(map);
  });
  map.on('mouseenter', clickLayer, () => { map.getCanvas().style.cursor = 'pointer'; });
  map.on('mouseleave', clickLayer, () => { map.getCanvas().style.cursor = ''; });
}

function addOfficialMapLayers(map) {
  addGeoLayer(map, 'official-seabed', state.official.seabed, '#a1845c', .07, 1);
  addGeoLayer(map, 'official-achare', state.official.achare, '#12a06a', .22, 2.2);
  addGeoLayer(map, 'official-fairway', state.official.fairwy, '#1687d9', .13, 2.2);
  addGeoLayer(map, 'official-resare', state.official.resare, '#df4655', .20, 2.4);
  addGeoLayer(map, 'official-cacem', state.official.cacem, '#f39b34', .14, 1.8);
}

function officialAnchorPage() {
  const o = state.official;
  const shomDate = o.achare?.marine_meta?.generated_at || o.status?.generated_at;
  const cacemDate = o.cacem?.marine_meta?.generated_at || o.status?.cacem?.updated_at;
  const avDate = o.avurnav?.generated_at;
  return `<main class="page map-page">${subHeader('Où mouiller','SHOM + CACEM + AVURNAV + conditions')}
    <div class="map-wrap"><div id="anchor-map" class="map tall-map"></div>
      <div class="legend">
        <span><i class="dot green"></i>Mouillage SHOM</span>
        <span><i class="dot red"></i>Restriction</span>
        <span><i class="dot" style="background:#1687d9"></i>Chenal</span>
        <span><i class="dot" style="background:#f39b34"></i>CACEM</span>
      </div>
    </div>
    <section class="anchor-sheet">
      <div class="sheet-title"><span class="anchor-big">${I('anchor',24)}</span><div><small>DONNÉES OFFICIELLES / OUVERTES</small><h2>Secteur Cannes · Lérins</h2></div><span class="confidence">${sourceHealth()}</span></div>
      <div class="metric-grid">
        <div><span>Zones de mouillage SHOM</span><b>${featureCount(o.achare)}</b></div>
        <div><span>Restrictions SHOM</span><b>${featureCount(o.resare)}</b></div>
        <div><span>AVURNAV proches</span><b>${o.avurnav?.items?.length || 0}</b></div>
      </div>
      <div class="notice good">${I('database',19)}<div><b>Snapshots locaux, pas d’appel critique au moment du départ</b><p>SHOM : ${dataTime(shomDate)} · CACEM : ${dataTime(cacemDate)} · AVURNAV : ${dataTime(avDate)}</p></div></div>
      <div class="notice warning">${I('triangle-alert',19)}<div><b>La carte aide à comprendre, elle ne garantit pas le droit de mouiller</b><p>Les tracés CACEM sont une interprétation. Les arrêtés, AVURNAV et textes officiels applicables restent la référence.</p></div></div>
      <a class="official-link" target="_blank" rel="noopener" href="https://diffusion.shom.fr/donnees/base-de-donnees-maritimes-et-littorales/reglementation-navigation.html">${I('external-link',17)}Source SHOM Réglementation-Navigation</a>
      <a class="official-link" target="_blank" rel="noopener" href="${regulations[2].url}">${I('external-link',17)}ZMEL officielle de Cannes</a>
    </section>${disclaimer()}
  </main>`;
}
pages.anchor = officialAnchorPage;

initAnchorMap = function () {
  const m = makeMap('anchor-map', { lat: 43.536, lng: 7.052 }, 13.8, true);
  if (!m) return;
  addUser(m);
  new maplibregl.Marker({ element: mapPin('anchor') }).setLngLat([7.052, 43.537]).setPopup(new maplibregl.Popup({ offset: 18 }).setHTML('<b>ZMEL Sainte-Anne</b><br><small>Consulter la réglementation officielle avant utilisation.</small>')).addTo(m);
  m.on('load', () => addOfficialMapLayers(m));
};

function officialAlertsPage() {
  const live = [];
  if (state.conditions.windKt > 15) live.push(['warning', 'Vent soutenu', `${Math.round(state.conditions.windKt)} nds actuellement`]);
  if (state.conditions.waveM > .8) live.push(['warning', 'Mer formée', `${state.conditions.waveM.toFixed(1)} m de vagues`]);
  if (!live.length) live.push(['good', 'Conditions immédiates', 'Aucun seuil météo du prototype n’est dépassé.']);
  const avurnavs = (state.official.avurnav?.items || []).slice(0, 12);
  return `<main class="page">${subHeader('Alertes','Conditions + AVURNAV + textes officiels')}
    <section class="alerts-list">
      ${live.map(a => `<div class="alert-card ${a[0]}">${I(a[0] === 'good' ? 'circle-check' : 'triangle-alert',20)}<div><small>CONDITIONS</small><h3>${esc(a[1])}</h3><p>${esc(a[2])}</p></div></div>`).join('')}
      ${avurnavs.length ? avurnavs.map(a => `<a target="_blank" rel="noopener" href="${esc(a.url || 'https://www.premar-mediterranee.gouv.fr/avis-urgents-aux-navigateurs')}" class="alert-card warning">${I('radio-tower',20)}<div><small>AVURNAV ${esc(a.number || '')}${a.distance_nm_from_cannes != null ? ` · ${esc(a.distance_nm_from_cannes)} NM de Cannes` : ''}</small><h3>${esc(a.title || 'Avis urgent aux navigateurs')}</h3><p>${esc((a.content || '').slice(0, 260))}${(a.content || '').length > 260 ? '…' : ''}</p><span>${esc(a.valid_until ? `Valide jusqu’au ${a.valid_until}` : 'En vigueur')}</span></div>${I('external-link',16)}</a>`).join('') : `<div class="alert-card info">${I('info',20)}<div><small>AVURNAV</small><h3>Snapshot en attente ou aucun avis proche</h3><p>Dernière synchro : ${esc(dataTime(state.official.avurnav?.generated_at))}</p></div></div>`}
      ${regulations.map(r => `<a target="_blank" rel="noopener" href="${r.url}" class="alert-card ${r.level}">${I(r.level === 'warning' ? 'triangle-alert' : r.level === 'good' ? 'anchor' : 'info',20)}<div><small>${r.ref}</small><h3>${r.title}</h3><p>${r.text}</p><span>${r.authority}${r.until ? ' · jusqu’au ' + r.until : ''}</span></div>${I('external-link',16)}</a>`).join('')}
    </section>
    <h2 class="section-title">État des sources</h2>
    <section class="source-list">${(state.official.status?.sources || []).map(s => `<div><div><b>${esc(s.source)}</b><span>${s.ok ? `Synchronisée · ${s.count ?? 0} éléments` : 'Indisponible · dernier snapshot conservé'}</span></div><span>${s.ok ? '✓' : '!'}</span></div>`).join('') || '<div><div><b>Synchronisation initiale</b><span>Le workflow GitHub Actions n’a pas encore produit son premier snapshot.</span></div></div>'}</section>
    ${disclaimer()}
  </main>`;
}
pages.alerts = officialAlertsPage;

function officialSatellitePage() {
  const c = state.conditions;
  const obs = state.official.sentinel?.observations || [];
  const cards = obs.map(o => {
    const label = o.sensor || 'Sentinel';
    const cloud = o.cloud_cover == null ? 'n/a' : `${Math.round(o.cloud_cover)} % nuages`;
    return `<a class="data-card" target="_blank" rel="noopener" href="${esc(o.catalog_url || 'https://dataspace.copernicus.eu/')}"><div class="row"><div><small>OBSERVATION RÉELLE</small><h3>${esc(label)}</h3></div><span class="confidence">${esc(cloud)}</span></div><p>Acquisition : <b>${esc(dataTime(o.datetime))}</b><br>${esc(o.id || '')}</p><span>${I('external-link',16)}Voir la fiche Copernicus</span></a>`;
  }).join('');
  return `<main class="page">${subHeader('Satellite','Copernicus STAC + conditions marines')}
    <div class="sat-tabs"><span class="active">Observations</span><span>Radar</span><span>Prévision</span></div>
    <section class="sat-hero"><div id="satellite-map" class="map sat-map"></div><div class="sat-label"><span>${I('satellite',18)}</span><div><small>COPERNICUS DATA SPACE</small><b>${obs.length ? `${obs.length} capteurs récents trouvés` : 'Synchronisation satellite en attente'}</b></div></div></section>
    <section class="science-grid"><div>${I('thermometer-sun')}<span>Température mer</span><b>${c.seaTemp.toFixed(1)} °C</b><small>provider marin prototype · ${freshness()}</small></div><div>${I('waves')}<span>Vagues</span><b>${c.waveM.toFixed(1)} m</b><small>${Math.round(c.wavePeriod)} s · ${compass(c.waveDir)}</small></div><div>${I('wind')}<span>Vent</span><b>${Math.round(c.windKt)} nds</b><small>${compass(c.windDir)} · ${freshness()}</small></div><div>${I('move-right')}<span>Courant</span><b>${c.currentKt.toFixed(1)} nds</b><small>${compass(c.currentDir)}</small></div></section>
    ${cards || `<section class="data-card"><div class="row"><div><small>PREMIER SYNC À LANCER</small><h3>Sentinel-1 + Sentinel-2</h3></div><span class="confidence">Open data</span></div><p>Le workflow interrogera le catalogue STAC Copernicus pour la zone Cannes/Lérins et conservera les métadonnées des acquisitions récentes.</p></section>`}
    <section class="data-card"><div class="row"><div><small>SENTINEL-3</small><h3>Collections détectées dans le catalogue</h3></div><span class="confidence">${state.official.sentinel?.sentinel3_collections_available?.length || 0}</span></div><p>Le pipeline inventorie aussi les collections Sentinel-3 disponibles afin de préparer température et couleur de l’océan sans afficher de fausse donnée « live ».</p></section>
    ${disclaimer()}
  </main>`;
}
pages.satellite = officialSatellitePage;

const originalInitMapWithOfficialData = initMap;
initMap = function () {
  originalInitMapWithOfficialData();
  if (state.screen === 'map' && state.map) {
    const map = state.map;
    map.on('load', () => addOfficialMapLayers(map));
  }
};

async function loadOfficialSnapshots() {
  const [avurnav, achare, resare, fairwy, seabed, cacem, sentinel, status] = await Promise.all([
    snapshot('avurnav.json', officialData.avurnav),
    snapshot('shom-achare.geojson', officialData.achare),
    snapshot('shom-resare.geojson', officialData.resare),
    snapshot('shom-fairwy.geojson', officialData.fairwy),
    snapshot('shom-seabed.geojson', officialData.seabed),
    snapshot('cacem-cannes.geojson', officialData.cacem),
    snapshot('sentinel-latest.json', officialData.sentinel),
    snapshot('source-status.json', officialData.status),
  ]);
  Object.assign(officialData, { avurnav, achare, resare, fairwy, seabed, cacem, sentinel, status, loaded: true });
  if (['anchor', 'alerts', 'satellite', 'map'].includes(state.screen)) render();
}

loadOfficialSnapshots();
